### ISSUE TITLE
http.client.RemoteDisconnected: Remote end closed connection without response

### ISSUE THREAD

**Issue by 9acca9** [rhgrant10/berserk#52]
Why i'm getting this errors sometimes, what could be that is generating this:

````
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.7/http/client.py", line 1336, in getresponse
    response.begin()
  File "/usr/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
```
`

**Comment by 9acca9** [comment]
I notice that this error appears randomly when i play against the AI. And it is weird because the mechanism is the same, of course, that when play against a human. 
I create a game against the Ai, like this:```

```
reto = berserk.clients.Challenges(session)
reto.create_ai(level, clock_limit, clock_increment, days=None, color=colorin, variant=None,position=None)

```

And, of course, the game begin. Im playing and ramdoly i get that error message.
